MODULE SRFGWRECHARGE_MOD
CONTAINS
SUBROUTINE SRFGWRECHARGE(KIDIA,KFDIA,KLON,KLEVS,&
 & PTSPHY,&
 & PSSDP3,&
 & YDSOIL,&
 & LDLAND,&
 & PRHSW)

USE PARKIND1        , ONLY : JPIM, JPRB
USE YOMHOOK         , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOS_SOIL        , ONLY : TSOIL
USE YOMSURF_SSDP_MOD, ONLY : SSDP3D_ID

! (C) Copyright 2026- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

!**** *SRFGWRECHARGE* - ADDS AN EXPLICIT CAPILLARY-RISE RECHARGE FROM THE
!                        WATER TABLE TO THE SOIL MOISTURE RIGHT-HAND SIDE,
!                        DRAWING DOWN A FINITE PROGNOSTIC AQUIFER

!     PURPOSE.
!     --------
!     THIRD OF THE "DEPTH TRILOGY" PROTOTYPES ALONGSIDE LEUNIFORMROOT
!     (ROOTING DEPTH) AND LEBEDROCKLIM (BEDROCK-LIMITED DRAINAGE). ADDS A
!     GARDNER (1958)-TYPE EXPONENTIAL CAPILLARY-RISE FLUX FROM THE WATER
!     TABLE INTO EVERY LAYER ABOVE IT, BOUNDED BY THAT LAYER'S OWN
!     SATURATED HYDRAULIC CONDUCTIVITY AND DECAYING WITH HEIGHT ABOVE THE
!     WATER TABLE AT THE VAN GENUCHTEN ALPHA RATE -- 1/ALPHA IS THE
!     CHARACTERISTIC CAPILLARY LENGTH FOR THAT SOIL TEXTURE IN VAN
!     GENUCHTEN THEORY, SO THIS USES ONLY PARAMETERS ECLAND ALREADY
!     COMPUTES (RWCONSM3D, RMVGALPHA3D), NOT NEW TUNABLE CONSTANTS BEYOND
!     THE AQUIFER SIZE ITSELF (RGWSPECYIELD, SEE BELOW).

!     IT IS PURELY ADDITIVE, LIKE SRFWVAPOR: THE LIQUID DIFFUSIVITY
!     MATRIX (*PCFW*) BUILT BY *SRFWEXC_VG* (OR *SRFWEXC*) IS NOT
!     TOUCHED, AND *SRFWDIF*/*SRFWINC* DOWNSTREAM ARE UNCHANGED.

!     UNLIKE THE FIRST VERSION OF THIS PROTOTYPE, RECHARGE IS NO LONGER
!     DRAWN FROM AN INFINITE, NON-DEPLETING WATER TABLE: THE WATER TABLE
!     DEPTH ITSELF (ZWTD BELOW) IS NOW A PROGNOSTIC QUANTITY THAT DEEPENS
!     AS THE CUMULATIVE CAPILLARY-RISE EXTRACTION ABOVE IT GROWS, DIVIDED
!     BY A SPECIFIC YIELD (DRAINABLE POROSITY) REPRESENTING THE SIZE OF
!     THE UNCONFINED AQUIFER -- THE SAME STORAGE-TO-WATER-TABLE-DEPTH
!     RELATIONSHIP USED BY NIU ET AL. (2007)'S SIMPLE GROUNDWATER SCHEME
!     FOR CLM, THE MOST WIDELY ADOPTED "SIMPLE BUCKET" APPROACH OF THIS
!     KIND IN LAND SURFACE MODELS. THIS ADDRESSES A REAL CONCERN RAISED
!     WHILE TESTING THE FIRST VERSION: AN INFINITE-SOURCE RECHARGE THAT
!     ULTIMATELY EXITS VIA LESSRO/VIC SATURATION-EXCESS RUNOFF (*QSB*)
!     COULD ARTIFICIALLY INFLATE SIMULATED RIVER DISCHARGE IF COUPLED TO
!     CAMA-FLOOD, SINCE THERE WAS NO ACCOUNTING FOR WHERE THAT WATER CAME
!     FROM. A DEPLETING, BEDROCK-BOUNDED AQUIFER SELF-LIMITS INSTEAD.
!     THIS VERSION ONLY IMPLEMENTS DEEPENING (EXTRACTION); A REPLENISHING
!     INFLOW TERM (E.G. FROM DEEP DRAINAGE PAST LEBEDROCKLIM) IS NATURAL
!     FOLLOW-ON WORK, NOT DONE HERE.

!     THE PROGNOSTIC WATER TABLE DEPTH IS HELD IN A SAVEd MODULE-LEVEL
!     ARRAY, NOT ECLAND'S OWN RESTART-CHECKPOINTED STATE: YDSOIL IS
!     INTENT(IN) THROUGHOUT THE ENTIRE CALL CHAIN UP TO SURFTSTP_CTL, SO
!     THREADING A GENUINELY MUTABLE FIELD THROUGH IT PROPERLY WOULD MEAN
!     CHANGING INTENT(IN)->INTENT(INOUT) AT EVERY LEVEL OF THAT CHAIN -- A
!     LARGER STRUCTURAL CHANGE THAN THIS PROTOTYPE WARRANTS. CONSEQUENCE:
!     THIS EVOLVES CORRECTLY WITHIN ONE CONTINUOUS EXECUTABLE INVOCATION
!     (INCLUDING ACROSS EVERY DR_HOOK-TIMED TIMESTEP OF A MULTI-YEAR
!     FORCING PERIOD), BUT *NOT* ACROSS THE OFFLINE DRIVER'S OWN NLOOP
!     SPIN-UP CONVENTION -- ecland_run_model.sh's NLOOP LOOP RE-INVOKES
!     THE EXECUTABLE AS A FRESH PROCESS FOR EACH RLOOP, READING THE
!     PREVIOUS LOOP'S RESTART FILE FOR SOIL MOISTURE/TEMPERATURE BUT NOT
!     FOR THIS MODULE-LEVEL VARIABLE, SO ZWTD RESETS TO RWTD AT THE START
!     OF EVERY RLOOP. VERIFIED EMPIRICALLY (SEE SUSSOIL.F90 COMMENTS).
!     PROPER MULTI-RLOOP/RESTART PERSISTENCE NEEDS REAL RESTART I/O
!     INTEGRATION, NOT DONE HERE. ALSO ONLY CORRECT FOR A SINGLE FIXED
!     NPROMA BLOCK (TRUE OF EVERY OFFLINE SINGLE-SITE TEST THIS PROJECT
!     HAS RUN) -- NOT YET SAFE FOR A GENUINE MULTI-BLOCK/GLOBAL DOMAIN,
!     WHERE DIFFERENT BLOCKS WOULD ALIAS THE SAME STORAGE.

!     RWTD (INITIAL WATER TABLE DEPTH) IS A SINGLE GLOBAL SCALAR FOR NOW,
!     NOT YET PER-GRIDPOINT -- SEE LEGWRECHARGE/RWTD IN YOS_SOIL.F90 FOR
!     THE "NO DATA AVAILABLE" DEFAULT RATIONALE (100M, INERT EVERYWHERE,
!     SAME CONVENTION AS RDBEDROCK). RDBEDROCK ALSO CAPS HOW DEEP ZWTD CAN
!     GO -- THE AQUIFER CANNOT DRAIN BELOW SOLID ROCK.

!**   INTERFACE.
!     ----------
!          *SRFGWRECHARGE* IS CALLED FROM *SURFTSTP*, ALONGSIDE
!     *SRFWVAPOR* -- AFTER *SRFWEXC_VG* or *SRFWEXC* (SO PRHSW ALREADY
!     HOLDS THE LIQUID BUDGET), BUT BEFORE *SRFWDIF*.

!     PARAMETER   DESCRIPTION                                    UNITS
!     ---------   -----------                                    -----

!     INPUT PARAMETERS (INTEGER):
!    *KIDIA*      START POINT
!    *KFDIA*      END POINT
!    *KLON*       NUMBER OF GRID POINTS PER PACKET
!    *KLEVS*      NUMBER OF ACTIVE SOIL-WATER LAYERS (KLEVS_WB AT THE
!                 CALL SITE, MATCHING THE SUBSEQUENT *SRFWDIF* CALL)

!     INPUT PARAMETERS (REAL):
!    *PTSPHY*     TIME STEP                                       S
!    *PSSDP3*     SPATIALLY DISTRIBUTED SOIL PARAMETERS (VAN
!                 GENUCHTEN ALPHA, SATURATED CONDUCTIVITY, ...)

!     INPUT PARAMETERS (LOGICAL):
!    *LDLAND*     LAND/SEA MASK (TRUE/FALSE)

!     INPUT PARAMETERS (DERIVED TYPE):
!    *YDSOIL*     SOIL PARAMETERS (RDAW LAYER THICKNESSES, RWTD INITIAL
!                 WATER TABLE DEPTH, RDBEDROCK LOWER BOUND, RGWSPECYIELD
!                 AQUIFER SPECIFIC YIELD)

!     UPDATED PARAMETERS (REAL):
!    *PRHSW*      RIGHT-HAND SIDE OF SOIL MOISTURE EQUATIONS,
!                 AS BUILT BY *SRFWEXC_VG* or *SRFWEXC*; THE RECHARGE
!                 FLUX IS ADDED TO IT IN PLACE.                 M**3/M**3

!     REFERENCE.
!     ----------
!     Gardner, W.R. (1958): Some steady-state solutions of the unsaturated
!     moisture flow equation with application to evaporation from a water
!     table. Soil Science, 85(4), 228-232.
!     Niu, G.-Y., Yang, Z.-L., Dickinson, R.E., Gulden, L.E., Su, H.
!     (2007): Development of a simple groundwater model for use in
!     climate models and evaluation with Gravity Recovery and Climate
!     Experiment data. JGR Atmospheres, 112, D07103.

!     Original
!     Prototype for the ecLand "depth trilogy" (rooting depth / bedrock /
!     water table), third of three. 2026-08-31
!     ------------------------------------------------------------------

IMPLICIT NONE

! Declaration of arguments

INTEGER(KIND=JPIM), INTENT(IN)   :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN)   :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN)   :: KLON
INTEGER(KIND=JPIM), INTENT(IN)   :: KLEVS

REAL(KIND=JPRB),    INTENT(IN)   :: PTSPHY
REAL(KIND=JPRB),    INTENT(IN)   :: PSSDP3(:,:,:)
TYPE(TSOIL),         INTENT(IN)  :: YDSOIL
LOGICAL,             INTENT(IN)  :: LDLAND(:)

REAL(KIND=JPRB),    INTENT(INOUT):: PRHSW(:,:)

!*         0.2    DECLARATION OF LOCAL VARIABLES.
!                 ----------- -- ----- ----------

REAL(KIND=JPRB) :: ZDEPTH_UPPER, ZDEPTH_MID, ZDIST, ZCAPFLUX, ZEXTRACT

INTEGER(KIND=JPIM) :: JK, JL
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

! Prototype prognostic aquifer water-table depth -- see the module-level
! restart/multi-block caveats above. Allocated and initialised from
! YDSOIL%RWTD on first call.
REAL(KIND=JPRB), ALLOCATABLE, SAVE :: ZWTD(:)

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('SRFGWRECHARGE_MOD:SRFGWRECHARGE',0,ZHOOK_HANDLE)

IF (.NOT. ALLOCATED(ZWTD)) THEN
  ALLOCATE(ZWTD(KLON))
  ZWTD(:) = YDSOIL%RWTD
ENDIF

ASSOCIATE(RDAW=>YDSOIL%RDAW, &
 & RWCONSM3D=>PSSDP3(:,:,SSDP3D_ID%NRWCONSM3D), &
 & RMVGALPHA3D=>PSSDP3(:,:,SSDP3D_ID%NRMVGALPHA3D) )

!*         1.    CAPILLARY-RISE SOURCE TERM PER LAYER (ZERO FOR ANY LAYER
!                AT OR BELOW THIS POINT'S CURRENT WATER TABLE DEPTH),
!                THEN DEEPEN THE AQUIFER BY THE TOTAL EXTRACTED THIS
!                TIMESTEP DIVIDED BY THE SPECIFIC YIELD (NIU ET AL. 2007
!                STORAGE-TO-DEPTH RELATIONSHIP), CAPPED AT RDBEDROCK.

DO JL=KIDIA,KFDIA
  IF (LDLAND(JL)) THEN
    ZEXTRACT = 0.0_JPRB
    ZDEPTH_UPPER = 0.0_JPRB
    DO JK=1,KLEVS
      ZDEPTH_MID = ZDEPTH_UPPER + 0.5_JPRB*RDAW(JK)
      ZDIST = ZWTD(JL) - ZDEPTH_MID
      IF (ZDIST > 0.0_JPRB) THEN
        ZCAPFLUX = RWCONSM3D(JL,JK)*EXP(-RMVGALPHA3D(JL,JK)*ZDIST)
        PRHSW(JL,JK) = PRHSW(JL,JK) + PTSPHY*ZCAPFLUX/RDAW(JK)
        ZEXTRACT = ZEXTRACT + PTSPHY*ZCAPFLUX ! water-equivalent depth (m), same convention as PRHSW*RDAW
      ENDIF
      ZDEPTH_UPPER = ZDEPTH_UPPER + RDAW(JK)
    ENDDO
    IF (ZEXTRACT > 0.0_JPRB) THEN
      ZWTD(JL) = MIN(YDSOIL%RDBEDROCK, ZWTD(JL) + ZEXTRACT/YDSOIL%RGWSPECYIELD)
    ENDIF
  ENDIF
ENDDO

END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('SRFGWRECHARGE_MOD:SRFGWRECHARGE',1,ZHOOK_HANDLE)

END SUBROUTINE SRFGWRECHARGE
END MODULE SRFGWRECHARGE_MOD
