MODULE SRFGWRECHARGE_MOD
CONTAINS
SUBROUTINE SRFGWRECHARGE(KIDIA,KFDIA,KLON,KLEVS,&
 & PTSPHY,&
 & PSSDP3,&
 & YDSOIL,&
 & LDLAND,&
 & PWSAM1M,&
 & PWTDM1M,&
 & PRHSW,&
 & PWTDE1)

USE PARKIND1        , ONLY : JPIM, JPRB
USE YOMHOOK         , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOS_SOIL        , ONLY : TSOIL
USE YOMSURF_SSDP_MOD, ONLY : SSDP3D_ID

! (C) Copyright 2026- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

!**** *SRFGWRECHARGE* - BIDIRECTIONAL WATER-TABLE/SOIL EXCHANGE: CAPILLARY-
!                        RISE EXTRACTION FROM A FINITE PROGNOSTIC AQUIFER,
!                        PLUS FREE-DRAINAGE RECHARGE BACK INTO IT

!     PURPOSE.
!     --------
!     THIRD OF THE "DEPTH TRILOGY" PROTOTYPES ALONGSIDE LEUNIFORMROOT
!     (ROOTING DEPTH) AND LEBEDROCKLIM (BEDROCK-LIMITED DRAINAGE). THE
!     PROGNOSTIC WATER TABLE DEPTH (*PWTDM1M*/*PWTDE1*) IS A GENUINE,
!     RESTART-CHECKPOINTED ECLAND STATE VARIABLE (SEE YOMGP1S0/1/A'S
!     WTDNU0/1/A AND RDSUPR'S 'WTD' CVARS2D ENTRY), NOT A MODULE-LEVEL
!     SAVE. IT EVOLVES IN BOTH DIRECTIONS:

!     (1) EXTRACTION (DEEPENS THE WATER TABLE): A GARDNER (1958)-TYPE
!         EXPONENTIAL CAPILLARY-RISE FLUX FROM THE WATER TABLE INTO EVERY
!         LAYER ABOVE IT, DECAYING WITH HEIGHT ABOVE THE WATER TABLE AT
!         THE VAN GENUCHTEN ALPHA RATE -- 1/ALPHA IS THE CHARACTERISTIC
!         CAPILLARY LENGTH FOR THAT SOIL TEXTURE. USES ONLY PARAMETERS
!         ECLAND ALREADY COMPUTES (RWCONSM3D, RMVGALPHA3D).

!     (2) RECHARGE (SHALLOWS THE WATER TABLE): A SIMPLE FREE-DRAINAGE
!         ESTIMATE OUT OF THE BOTTOM SOIL LAYER, ACTIVE ONLY WHEN THAT
!         LAYER'S DEGREE OF SATURATION EXCEEDS A THRESHOLD (RGWDRAINSE,
!         A CRUDE FIELD-CAPACITY PROXY -- ECLAND HAS NO EXPLICIT FIELD
!         CAPACITY PARAMETER), RAMPING LINEARLY TO THE LAYER'S OWN
!         RWCONSM3D AT FULL SATURATION. THIS IS A DELIBERATE
!         SIMPLIFICATION: IT DOES NOT TAP THE ACTUAL DIAGNOSED DRAINAGE
!         FLUX LEAVING THE COLUMN IN *SRFWEXC_VG* (POST-LEBEDROCKLIM
!         TAPER), WHICH WOULD REQUIRE A NEW DIAGNOSTIC THREADED THROUGH
!         THE WHOLE CALL CHAIN. CONSEQUENCE: RECHARGE HERE IS BEST READ
!         AS "SOME OF THE WATER THAT WOULD OTHERWISE HAVE DRAINED PAST
!         THE BOTTOM LAYER NOW GOES TO THE AQUIFER INSTEAD OF TOWARDS
!         *QSB* (LESSRO/VIC SATURATION-EXCESS RUNOFF)" -- A WET ANOMALY
!         SHOULD THEREFORE SHOW A SMALLER QSB INCREASE THAN THE FIRST,
!         ONE-WAY VERSION OF THIS PROTOTYPE, NOT ZERO, SINCE THE TWO
!         DIAGNOSE DRAINAGE DIFFERENTLY.

!     BOTH TERMS CONVERT A WATER-EQUIVALENT DEPTH (M) TO A WATER-TABLE-
!     DEPTH CHANGE VIA THE SPECIFIC YIELD (DRAINABLE POROSITY, RGWSPECYIELD
!     -- SIZE OF THE UNCONFINED AQUIFER), THE SAME STORAGE-TO-DEPTH
!     RELATIONSHIP USED BY NIU ET AL. (2007)'S SIMPLE GROUNDWATER SCHEME
!     FOR CLM. THE RESULT IS EXPRESSED AS A TENDENCY (*PWTDE1*, M/S), NOT
!     AN IN-PLACE UPDATE: ECLAND INTEGRATES GP1=GP0+TDT*ZGPE_STACK FOR
!     EVERY PROGNOSTIC FIELD GENERICALLY (SEE CPG1S.F90), SO THE WATER
!     TABLE DEPTH IS CLAMPED HERE BY LIMITING THE TENDENCY ITSELF (NEVER
!     LET IT DEEPEN PAST RDBEDROCK -- SOLID ROCK -- OR SHALLOW PAST
!     RGWTD_MIN), NOT BY REASSIGNING STATE.

!     IT IS PURELY ADDITIVE, LIKE SRFWVAPOR: THE LIQUID DIFFUSIVITY
!     MATRIX (*PCFW*) BUILT BY *SRFWEXC_VG* (OR *SRFWEXC*) IS NOT
!     TOUCHED, AND *SRFWDIF*/*SRFWINC* DOWNSTREAM ARE UNCHANGED.

!     THE "NO DATA AVAILABLE" INITIAL/DEFAULT WATER TABLE DEPTH (100M, A
!     SINGLE GLOBAL VALUE FOR NOW, NOT YET PER-GRIDPOINT) LIVES WHERE THE
!     FIELD ITSELF IS INITIALISED (SUGP1S.F90 COLD START, RDSUPR.F90'S
!     "MISSING FROM RESTART FILE" FALLBACK), NOT IN YOS_SOIL.F90 -- SEE
!     LEGWRECHARGE'S COMMENT THERE. RDBEDROCK CAPS HOW DEEP THE WATER TABLE
!     CAN GO -- THE AQUIFER CANNOT DRAIN BELOW SOLID ROCK.

!**   INTERFACE.
!     ----------
!          *SRFGWRECHARGE* IS CALLED FROM *SURFTSTP_CTL*, ALONGSIDE
!     *SRFWVAPOR* -- AFTER *SRFWEXC_VG* or *SRFWEXC* (SO PRHSW ALREADY
!     HOLDS THE LIQUID BUDGET), BUT BEFORE *SRFWDIF*.

!     PARAMETER   DESCRIPTION                                    UNITS
!     ---------   -----------                                    -----

!     INPUT PARAMETERS (INTEGER):
!    *KIDIA*      START POINT
!    *KFDIA*      END POINT
!    *KLON*       NUMBER OF GRID POINTS PER PACKET
!    *KLEVS*      NUMBER OF ACTIVE SOIL-WATER LAYERS (KLEVS_WB AT THE
!                 CALL SITE, MATCHING THE SUBSEQUENT *SRFWDIF* CALL)

!     INPUT PARAMETERS (REAL):
!    *PTSPHY*     TIME STEP                                       S
!    *PSSDP3*     SPATIALLY DISTRIBUTED SOIL PARAMETERS (VAN
!                 GENUCHTEN ALPHA, SATURATED/RESIDUAL MOISTURE,
!                 REFERENCE CONDUCTIVITY, ...)
!    *PWSAM1M*    SOIL MOISTURE                                M**3/M**3
!    *PWTDM1M*    WATER-TABLE DEPTH AT THE START OF THIS TIMESTEP    M

!     INPUT PARAMETERS (LOGICAL):
!    *LDLAND*     LAND/SEA MASK (TRUE/FALSE)

!     INPUT PARAMETERS (DERIVED TYPE):
!    *YDSOIL*     SOIL PARAMETERS (RDAW LAYER THICKNESSES, RDBEDROCK LOWER
!                 BOUND, RGWSPECYIELD AQUIFER SPECIFIC YIELD)

!     UPDATED PARAMETERS (REAL):
!    *PRHSW*      RIGHT-HAND SIDE OF SOIL MOISTURE EQUATIONS,
!                 AS BUILT BY *SRFWEXC_VG* or *SRFWEXC*; THE EXTRACTION
!                 AND RECHARGE FLUXES ARE ADDED TO IT IN PLACE. M**3/M**3
!    *PWTDE1*     WATER-TABLE DEPTH TENDENCY, ACCUMULATED IN PLACE   M/S

!     REFERENCE.
!     ----------
!     Gardner, W.R. (1958): Some steady-state solutions of the unsaturated
!     moisture flow equation with application to evaporation from a water
!     table. Soil Science, 85(4), 228-232.
!     Niu, G.-Y., Yang, Z.-L., Dickinson, R.E., Gulden, L.E., Su, H.
!     (2007): Development of a simple groundwater model for use in
!     climate models and evaluation with Gravity Recovery and Climate
!     Experiment data. JGR Atmospheres, 112, D07103.

!     Original
!     Prototype for the ecLand "depth trilogy" (rooting depth / bedrock /
!     water table), third of three. 2026-08-31
!     Made genuinely prognostic and bidirectional. 2026-08-31
!     ------------------------------------------------------------------

IMPLICIT NONE

! Declaration of arguments

INTEGER(KIND=JPIM), INTENT(IN)   :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN)   :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN)   :: KLON
INTEGER(KIND=JPIM), INTENT(IN)   :: KLEVS

REAL(KIND=JPRB),    INTENT(IN)   :: PTSPHY
REAL(KIND=JPRB),    INTENT(IN)   :: PSSDP3(:,:,:)
TYPE(TSOIL),         INTENT(IN)  :: YDSOIL
LOGICAL,             INTENT(IN)  :: LDLAND(:)
REAL(KIND=JPRB),    INTENT(IN)   :: PWSAM1M(:,:)
REAL(KIND=JPRB),    INTENT(IN)   :: PWTDM1M(:)

REAL(KIND=JPRB),    INTENT(INOUT):: PRHSW(:,:)
REAL(KIND=JPRB),    INTENT(INOUT):: PWTDE1(:)

!*         0.2    DECLARATION OF LOCAL VARIABLES.
!                 ----------- -- ----- ----------

! Floor on water-table depth: keeps the aquifer strictly below the active
! soil-water profile and away from a nonphysical depth-zero singularity in
! the tendency-clamp arithmetic below.
REAL(KIND=JPRB), PARAMETER :: RGWTD_MIN=0.5_JPRB

! Degree-of-saturation threshold above which the bottom layer is taken to
! free-drain towards the aquifer -- a crude field-capacity proxy, since
! ecLand has no explicit field-capacity parameter in PSSDP3. Calibrated
! (not the original 0.75 guess) against a single-loop drift test at AU-Tum:
! starting the water table at the Fan et al. (2017) estimate for that site
! (45m) and requiring it hold there rather than collapse toward the
! recharge-dominated ~2.4m attractor 0.75 produced. Verified across the
! 42-site PLUMBER2 network, each initialised at its own Fan et al. depth:
! held within round-off at 29/42 sites spanning 6.9-98.3m. Known limits,
! not yet fixed: 9/42 sites still collapse toward a shared ~4-5.5m
! attractor regardless of this threshold (their van Genuchten alpha makes
! extraction dominant at moderate depth -- a single global threshold can't
! fix a soil-texture-dependent effect); 3/42 sites have a Fan et al. depth
! beyond RDBEDROCK's own 100m no-data default and get clamped there, a
! separate artifact unrelated to this threshold.
REAL(KIND=JPRB), PARAMETER :: RGWDRAINSE=0.98_JPRB

REAL(KIND=JPRB) :: ZDEPTH_UPPER, ZDEPTH_MID, ZDIST, ZCAPFLUX, ZEXTRACT
REAL(KIND=JPRB) :: ZSE, ZDRAINFRAC, ZDRAIN, ZRECHARGE, ZDWTDDT

INTEGER(KIND=JPIM) :: JK, JL, JKBOT
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('SRFGWRECHARGE_MOD:SRFGWRECHARGE',0,ZHOOK_HANDLE)

JKBOT=KLEVS

ASSOCIATE(RDAW=>YDSOIL%RDAW, &
 & RWCONSM3D=>PSSDP3(:,:,SSDP3D_ID%NRWCONSM3D), &
 & RMVGALPHA3D=>PSSDP3(:,:,SSDP3D_ID%NRMVGALPHA3D), &
 & RWSATM3D=>PSSDP3(:,:,SSDP3D_ID%NRWSATM3D), &
 & RWRESTM3D=>PSSDP3(:,:,SSDP3D_ID%NRWRESTM3D) )

DO JL=KIDIA,KFDIA
  IF (LDLAND(JL)) THEN

!*         1.    CAPILLARY-RISE EXTRACTION PER LAYER (ZERO FOR ANY LAYER
!                AT OR BELOW THIS POINT'S CURRENT WATER TABLE DEPTH).

    ZEXTRACT = 0.0_JPRB
    ZDEPTH_UPPER = 0.0_JPRB
    DO JK=1,KLEVS
      ZDEPTH_MID = ZDEPTH_UPPER + 0.5_JPRB*RDAW(JK)
      ZDIST = PWTDM1M(JL) - ZDEPTH_MID
      IF (ZDIST > 0.0_JPRB) THEN
        ZCAPFLUX = RWCONSM3D(JL,JK)*EXP(-RMVGALPHA3D(JL,JK)*ZDIST)
        PRHSW(JL,JK) = PRHSW(JL,JK) + PTSPHY*ZCAPFLUX/RDAW(JK)
        ZEXTRACT = ZEXTRACT + PTSPHY*ZCAPFLUX ! water-equivalent depth (m)
      ENDIF
      ZDEPTH_UPPER = ZDEPTH_UPPER + RDAW(JK)
    ENDDO

!*         2.    FREE-DRAINAGE RECHARGE FROM THE BOTTOM LAYER, ACTIVE ONLY
!                ABOVE THE RGWDRAINSE SATURATION THRESHOLD.

    ZSE = (PWSAM1M(JL,JKBOT)-RWRESTM3D(JL,JKBOT)) / &
     & MAX(RWSATM3D(JL,JKBOT)-RWRESTM3D(JL,JKBOT),1.E-6_JPRB)
    ZSE = MAX(0.0_JPRB,MIN(1.0_JPRB,ZSE))
    ZDRAINFRAC = MAX(0.0_JPRB,(ZSE-RGWDRAINSE)/(1.0_JPRB-RGWDRAINSE))
    ZDRAIN = RWCONSM3D(JL,JKBOT)*ZDRAINFRAC
    PRHSW(JL,JKBOT) = PRHSW(JL,JKBOT) - PTSPHY*ZDRAIN/RDAW(JKBOT)
    ZRECHARGE = PTSPHY*ZDRAIN ! water-equivalent depth (m)

!*         3.    NET WATER-TABLE-DEPTH TENDENCY, CLAMPED SO THE IMPLIED
!                END-OF-STEP DEPTH STAYS WITHIN [RGWTD_MIN, RDBEDROCK].

    ZDWTDDT = (ZEXTRACT-ZRECHARGE)/(YDSOIL%RGWSPECYIELD*PTSPHY)
    ZDWTDDT = MAX(ZDWTDDT,(RGWTD_MIN-PWTDM1M(JL))/PTSPHY)
    ZDWTDDT = MIN(ZDWTDDT,(YDSOIL%RDBEDROCK-PWTDM1M(JL))/PTSPHY)

    PWTDE1(JL) = PWTDE1(JL) + ZDWTDDT

  ENDIF
ENDDO

END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('SRFGWRECHARGE_MOD:SRFGWRECHARGE',1,ZHOOK_HANDLE)

END SUBROUTINE SRFGWRECHARGE
END MODULE SRFGWRECHARGE_MOD
