MODULE SRFGWRECHARGE_MOD
CONTAINS
SUBROUTINE SRFGWRECHARGE(KIDIA,KFDIA,KLON,KLEVS,&
 & PTSPHY,&
 & PSSDP3,&
 & YDSOIL,&
 & LDLAND,&
 & PWTDM1M,&
 & PGWDRAINFLUX,&
 & PSDOR,&
 & PRHSW,&
 & PWTDE1,&
 & PGWDRAINUSED)

USE PARKIND1        , ONLY : JPIM, JPRB
USE YOMHOOK         , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOS_SOIL        , ONLY : TSOIL
USE YOMSURF_SSDP_MOD, ONLY : SSDP3D_ID
USE YOS_THF         , ONLY : RHOH2O

! (C) Copyright 2026- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

!**** *SRFGWRECHARGE* - BIDIRECTIONAL WATER-TABLE/SOIL EXCHANGE: CAPILLARY-
!                        RISE EXTRACTION FROM A FINITE PROGNOSTIC AQUIFER,
!                        PLUS FREE-DRAINAGE RECHARGE BACK INTO IT

!     PURPOSE.
!     --------
!     THIRD OF THE "DEPTH TRILOGY" PROTOTYPES ALONGSIDE LEUNIFORMROOT
!     (ROOTING DEPTH) AND LEBEDROCKLIM (BEDROCK-LIMITED DRAINAGE). THE
!     PROGNOSTIC WATER TABLE DEPTH (*PWTDM1M*/*PWTDE1*) IS A GENUINE,
!     RESTART-CHECKPOINTED ECLAND STATE VARIABLE (SEE YOMGP1S0/1/A'S
!     WTDNU0/1/A AND RDSUPR'S 'WTD' CVARS2D ENTRY), NOT A MODULE-LEVEL
!     SAVE. IT EVOLVES IN BOTH DIRECTIONS:

!     (1) EXTRACTION (DEEPENS THE WATER TABLE): A GARDNER (1958)-TYPE
!         EXPONENTIAL CAPILLARY-RISE FLUX FROM THE WATER TABLE INTO EVERY
!         LAYER ABOVE IT, DECAYING WITH HEIGHT ABOVE THE WATER TABLE AT
!         THE VAN GENUCHTEN ALPHA RATE -- 1/ALPHA IS THE CHARACTERISTIC
!         CAPILLARY LENGTH FOR THAT SOIL TEXTURE. USES ONLY PARAMETERS
!         ECLAND ALREADY COMPUTES (RWCONSM3D, RMVGALPHA3D).

!     (2) RECHARGE (SHALLOWS THE WATER TABLE): A FRACTION OF THE ACTUAL
!         GRAVITY-DRAINAGE FLUX LEAVING THE BOTTOM SOIL LAYER, AS DIAGNOSED
!         BY *SRFWEXC_VG* (PSAWGFL/ZSAWGFL AT JK=KLEVS_WB -- ALREADY
!         POST-LEBEDROCKLIM TAPER AND POST-LEFRZFLOOR FLOOR), PASSED IN
!         HERE AS *PGWDRAINFLUX*. NOTE *PROFD* -- WHAT THIS FLUX WOULD
!         OTHERWISE ENTIRELY BECOME -- IS QSB IN ECLAND'S OWN ACCOUNTING,
!         AND IS PURELY THIS GRAVITY-DRAINAGE TERM: THE LESSRO/VIC
!         SATURATION-EXCESS MECHANISM FEEDS *PROFS* (QS) SEPARATELY, NOT
!         QSB, SO THE TWO ARE NOT ENTANGLED HERE.
!
!         DIVERTING THE FULL FLUX TO THE AQUIFER (THE FIRST VERSION OF
!         THIS FIX) IS ITS OWN OVER-SIMPLIFICATION: PHYSICALLY, DRAINAGE
!         REACHING A WATER TABLE SPLITS BETWEEN RECHARGING LOCAL STORAGE
!         AND CONTINUING DOWN-GRADIENT AS LATERAL BASEFLOW, NOT ONE OR THE
!         OTHER. THE SPLIT IS SET HERE BY *PSDOR*, THE SAME SUBGRID
!         OROGRAPHY STANDARD DEVIATION *SRFWEXC_VG*'S OWN LESSRO/VIC BLOCK
!         ALREADY USES TO BUILD ITS SUBGRID SATURATION HETEROGENEITY TERM
!         (ZROEFF) -- SAME EQUATION SHAPE, BUT DELIBERATELY NOT THE SAME
!         RSIGORMIN/RSIGORMAX SCALE: THOSE ARE TUNED FOR LESSRO'S OWN
!         PURPOSE AND, REUSED AS-IS, GIVE NEAR-100% VERTICAL RECHARGE FOR
!         ALMOST EVERY REAL PLUMBER2 SITE REGARDLESS OF TERRAIN (SEE THE
!         DEDICATED RGWLATSIGMIN/RGWLATSIGMAX BELOW, CALIBRATED AGAINST
!         THIS NETWORK'S OWN PSDOR DISTRIBUTION INSTEAD). RUGGED
!         TERRAIN (HIGH PSDOR) IS TAKEN TO DRAIN MOSTLY LATERALLY (LITTLE
!         LOCAL AQUIFER BUILD-UP); FLAT TERRAIN (LOW PSDOR) IS TAKEN TO
!         RECHARGE MOSTLY VERTICALLY. THIS IS AN HONEST REUSE OF AN
!         EXISTING OROGRAPHIC HETEROGENEITY PROXY, NOT A DERIVED PHYSICAL
!         LAW, AND SHOULD BE TREATED WITH THE SAME SCRUTINY.
!
!         *PGWDRAINUSED* REPORTS THE FRACTION ACTUALLY DIVERTED SO THE
!         CALLER CAN SUBTRACT IT FROM WHAT REACHES *PROFD*/QSB -- OTHERWISE
!         THE SAME WATER WOULD BE COUNTED TWICE. CONSEQUENCE FOR A WET
!         ANOMALY: QSB DROPS BY THE RECHARGED FRACTION ONLY, NOT THE WHOLE
!         DRAINAGE FLUX -- THE REMAINDER CONTINUES AS LATERAL BASEFLOW
!         EXACTLY AS BEFORE THIS PROTOTYPE EXISTED.

!     BOTH TERMS CONVERT A WATER-EQUIVALENT DEPTH (M) TO A WATER-TABLE-
!     DEPTH CHANGE VIA THE SPECIFIC YIELD (DRAINABLE POROSITY, RGWSPECYIELD
!     -- SIZE OF THE UNCONFINED AQUIFER), THE SAME STORAGE-TO-DEPTH
!     RELATIONSHIP USED BY NIU ET AL. (2007)'S SIMPLE GROUNDWATER SCHEME
!     FOR CLM. THE RESULT IS EXPRESSED AS A TENDENCY (*PWTDE1*, M/S), NOT
!     AN IN-PLACE UPDATE: ECLAND INTEGRATES GP1=GP0+TDT*ZGPE_STACK FOR
!     EVERY PROGNOSTIC FIELD GENERICALLY (SEE CPG1S.F90), SO THE WATER
!     TABLE DEPTH IS CLAMPED HERE BY LIMITING THE TENDENCY ITSELF (NEVER
!     LET IT DEEPEN PAST RDBEDROCK -- SOLID ROCK -- OR SHALLOW PAST
!     RGWTD_MIN), NOT BY REASSIGNING STATE.

!     IT IS PURELY ADDITIVE, LIKE SRFWVAPOR: THE LIQUID DIFFUSIVITY
!     MATRIX (*PCFW*) BUILT BY *SRFWEXC_VG* (OR *SRFWEXC*) IS NOT
!     TOUCHED, AND *SRFWDIF*/*SRFWINC* DOWNSTREAM ARE UNCHANGED.

!     THE "NO DATA AVAILABLE" INITIAL/DEFAULT WATER TABLE DEPTH (100M, A
!     SINGLE GLOBAL VALUE FOR NOW, NOT YET PER-GRIDPOINT) LIVES WHERE THE
!     FIELD ITSELF IS INITIALISED (SUGP1S.F90 COLD START, RDSUPR.F90'S
!     "MISSING FROM RESTART FILE" FALLBACK), NOT IN YOS_SOIL.F90 -- SEE
!     LEGWRECHARGE'S COMMENT THERE. RDBEDROCK CAPS HOW DEEP THE WATER TABLE
!     CAN GO -- THE AQUIFER CANNOT DRAIN BELOW SOLID ROCK.

!**   INTERFACE.
!     ----------
!          *SRFGWRECHARGE* IS CALLED FROM *SURFTSTP_CTL*, ALONGSIDE
!     *SRFWVAPOR* -- AFTER *SRFWEXC_VG* or *SRFWEXC* (SO PRHSW ALREADY
!     HOLDS THE LIQUID BUDGET), BUT BEFORE *SRFWDIF*.

!     PARAMETER   DESCRIPTION                                    UNITS
!     ---------   -----------                                    -----

!     INPUT PARAMETERS (INTEGER):
!    *KIDIA*      START POINT
!    *KFDIA*      END POINT
!    *KLON*       NUMBER OF GRID POINTS PER PACKET
!    *KLEVS*      NUMBER OF ACTIVE SOIL-WATER LAYERS (KLEVS_WB AT THE
!                 CALL SITE, MATCHING THE SUBSEQUENT *SRFWDIF* CALL)

!     INPUT PARAMETERS (REAL):
!    *PTSPHY*     TIME STEP                                       S
!    *PSSDP3*     SPATIALLY DISTRIBUTED SOIL PARAMETERS (VAN
!                 GENUCHTEN ALPHA, SATURATED/RESIDUAL MOISTURE,
!                 REFERENCE CONDUCTIVITY, ...)
!    *PWTDM1M*    WATER-TABLE DEPTH AT THE START OF THIS TIMESTEP    M
!    *PGWDRAINFLUX* GRAVITY-DRAINAGE FLUX OUT OF THE BOTTOM LAYER,
!                 AS DIAGNOSED BY SRFWEXC_VG (PSAWGFL AT KLEVS_WB,
!                 POST-LEBEDROCKLIM TAPER)                    KG/M**2/S
!    *PSDOR*      SUBGRID STANDARD DEVIATION OF OROGRAPHY -- SETS THE
!                 LATERAL/VERTICAL PARTITION OF PGWDRAINFLUX, SAME
!                 PARAMETER SRFWEXC_VG'S OWN LESSRO/VIC BLOCK USES        M

!     INPUT PARAMETERS (LOGICAL):
!    *LDLAND*     LAND/SEA MASK (TRUE/FALSE)

!     INPUT PARAMETERS (DERIVED TYPE):
!    *YDSOIL*     SOIL PARAMETERS (RDAW LAYER THICKNESSES, RDBEDROCK LOWER
!                 BOUND, RGWSPECYIELD AQUIFER SPECIFIC YIELD)

!     UPDATED PARAMETERS (REAL):
!    *PRHSW*      RIGHT-HAND SIDE OF SOIL MOISTURE EQUATIONS,
!                 AS BUILT BY *SRFWEXC_VG* or *SRFWEXC*; THE EXTRACTION
!                 AND RECHARGE FLUXES ARE ADDED TO IT IN PLACE. M**3/M**3
!    *PWTDE1*     WATER-TABLE DEPTH TENDENCY, ACCUMULATED IN PLACE   M/S

!     OUTPUT PARAMETERS (REAL):
!    *PGWDRAINUSED* PORTION OF *PGWDRAINFLUX* DIVERTED TO THE AQUIFER --
!                 SUBTRACT FROM THE SAME FLUX BEFORE IT REACHES PROFD/QSB
!                 TO AVOID DOUBLE-COUNTING                    KG/M**2/S

!     REFERENCE.
!     ----------
!     Gardner, W.R. (1958): Some steady-state solutions of the unsaturated
!     moisture flow equation with application to evaporation from a water
!     table. Soil Science, 85(4), 228-232.
!     Niu, G.-Y., Yang, Z.-L., Dickinson, R.E., Gulden, L.E., Su, H.
!     (2007): Development of a simple groundwater model for use in
!     climate models and evaluation with Gravity Recovery and Climate
!     Experiment data. JGR Atmospheres, 112, D07103.

!     Original
!     Prototype for the ecLand "depth trilogy" (rooting depth / bedrock /
!     water table), third of three. 2026-08-31
!     Made genuinely prognostic and bidirectional. 2026-08-31
!     Recharge now uses SRFWEXC_VG's own diagnosed drainage flux instead
!     of a separately-calibrated saturation threshold. 2026-09-01
!     Recharge now takes only an orography-set fraction of that flux,
!     leaving the rest as lateral baseflow (PROFD/Qsb) -- diverting all
!     of it was itself an over-simplification. 2026-09-02
!     ------------------------------------------------------------------

IMPLICIT NONE

! Declaration of arguments

INTEGER(KIND=JPIM), INTENT(IN)   :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN)   :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN)   :: KLON
INTEGER(KIND=JPIM), INTENT(IN)   :: KLEVS

REAL(KIND=JPRB),    INTENT(IN)   :: PTSPHY
REAL(KIND=JPRB),    INTENT(IN)   :: PSSDP3(:,:,:)
TYPE(TSOIL),         INTENT(IN)  :: YDSOIL
LOGICAL,             INTENT(IN)  :: LDLAND(:)
REAL(KIND=JPRB),    INTENT(IN)   :: PWTDM1M(:)
REAL(KIND=JPRB),    INTENT(IN)   :: PGWDRAINFLUX(:)
REAL(KIND=JPRB),    INTENT(IN)   :: PSDOR(:)

REAL(KIND=JPRB),    INTENT(INOUT):: PRHSW(:,:)
REAL(KIND=JPRB),    INTENT(INOUT):: PWTDE1(:)
REAL(KIND=JPRB),    INTENT(OUT)  :: PGWDRAINUSED(:)

!*         0.2    DECLARATION OF LOCAL VARIABLES.
!                 ----------- -- ----- ----------

! Floor on water-table depth: keeps the aquifer strictly below the active
! soil-water profile and away from a nonphysical depth-zero singularity in
! the tendency-clamp arithmetic below.
REAL(KIND=JPRB), PARAMETER :: RGWTD_MIN=0.5_JPRB

! Deliberately NOT the same as YDSOIL%RSIGORMIN/RSIGORMAX: those are
! calibrated for LESSRO's own subgrid-saturation purpose and, reused
! as-is here, give f_recharge~1 (all vertical, no lateral) for nearly
! every real PLUMBER2 site -- even alpine ones -- since that scheme's
! scale simply isn't the right one for this question. These two are
! calibrated instead against the 42-site PLUMBER2 network's own PSDOR
! distribution (p10~7m, median~38m, p90~248m): flat below ~10m, and
! reaching a roughly even split by the more rugged end (~150-250m) of
! that range, rather than reusing an unrelated scheme's tuning.
REAL(KIND=JPRB), PARAMETER :: RGWLATSIGMIN=10.0_JPRB
REAL(KIND=JPRB), PARAMETER :: RGWLATSIGMAX=150.0_JPRB

REAL(KIND=JPRB) :: ZDEPTH_UPPER, ZDEPTH_MID, ZDIST, ZCAPFLUX, ZEXTRACT
REAL(KIND=JPRB) :: ZDRAIN, ZRECHARGE, ZDWTDDT, ZROEFF, ZFRECHARGE

INTEGER(KIND=JPIM) :: JK, JL, JKBOT
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('SRFGWRECHARGE_MOD:SRFGWRECHARGE',0,ZHOOK_HANDLE)

JKBOT=KLEVS

ASSOCIATE(RDAW=>YDSOIL%RDAW, &
 & RWCONSM3D=>PSSDP3(:,:,SSDP3D_ID%NRWCONSM3D), &
 & RMVGALPHA3D=>PSSDP3(:,:,SSDP3D_ID%NRMVGALPHA3D) )

DO JL=KIDIA,KFDIA
  IF (LDLAND(JL)) THEN

!*         1.    CAPILLARY-RISE EXTRACTION PER LAYER (ZERO FOR ANY LAYER
!                AT OR BELOW THIS POINT'S CURRENT WATER TABLE DEPTH).

    ZEXTRACT = 0.0_JPRB
    ZDEPTH_UPPER = 0.0_JPRB
    DO JK=1,KLEVS
      ZDEPTH_MID = ZDEPTH_UPPER + 0.5_JPRB*RDAW(JK)
      ZDIST = PWTDM1M(JL) - ZDEPTH_MID
      IF (ZDIST > 0.0_JPRB) THEN
        ZCAPFLUX = RWCONSM3D(JL,JK)*EXP(-RMVGALPHA3D(JL,JK)*ZDIST)
        PRHSW(JL,JK) = PRHSW(JL,JK) + PTSPHY*ZCAPFLUX/RDAW(JK)
        ZEXTRACT = ZEXTRACT + PTSPHY*ZCAPFLUX ! water-equivalent depth (m)
      ENDIF
      ZDEPTH_UPPER = ZDEPTH_UPPER + RDAW(JK)
    ENDDO

!*         2.    RECHARGE = AN OROGRAPHY-SET FRACTION OF THE ACTUAL
!                GRAVITY-DRAINAGE FLUX SRFWEXC_VG DIAGNOSED LEAVING THE
!                BOTTOM LAYER -- THE REST STAYS LATERAL (PROFD/QSB).
!                SAME ZROEFF SHAPE AS SRFWEXC_VG'S OWN LESSRO BLOCK:
!                ~0 (ALL RECHARGE) ON FLAT TERRAIN, ~1 (ALL LATERAL) ON
!                RUGGED TERRAIN, NO NEW TUNABLE CONSTANT.

    ZROEFF = MAX(0.0_JPRB,(PSDOR(JL)-RGWLATSIGMIN))/(PSDOR(JL)+RGWLATSIGMAX)
    ZFRECHARGE = 1.0_JPRB - MIN(1.0_JPRB,MAX(0.0_JPRB,ZROEFF))

    ZDRAIN = ZFRECHARGE*PGWDRAINFLUX(JL)/RHOH2O ! kg/m2/s -> m/s
    PRHSW(JL,JKBOT) = PRHSW(JL,JKBOT) - PTSPHY*ZDRAIN/RDAW(JKBOT)
    ZRECHARGE = PTSPHY*ZDRAIN ! water-equivalent depth (m)
    PGWDRAINUSED(JL) = ZFRECHARGE*PGWDRAINFLUX(JL)

!*         3.    NET WATER-TABLE-DEPTH TENDENCY, CLAMPED SO THE IMPLIED
!                END-OF-STEP DEPTH STAYS WITHIN [RGWTD_MIN, RDBEDROCK].

    ZDWTDDT = (ZEXTRACT-ZRECHARGE)/(YDSOIL%RGWSPECYIELD*PTSPHY)
    ZDWTDDT = MAX(ZDWTDDT,(RGWTD_MIN-PWTDM1M(JL))/PTSPHY)
    ZDWTDDT = MIN(ZDWTDDT,(YDSOIL%RDBEDROCK-PWTDM1M(JL))/PTSPHY)

    PWTDE1(JL) = PWTDE1(JL) + ZDWTDDT

  ELSE
    PGWDRAINUSED(JL) = 0.0_JPRB
  ENDIF
ENDDO

END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('SRFGWRECHARGE_MOD:SRFGWRECHARGE',1,ZHOOK_HANDLE)

END SUBROUTINE SRFGWRECHARGE
END MODULE SRFGWRECHARGE_MOD
