MODULE SRFWVAPOR_MOD
CONTAINS
SUBROUTINE SRFWVAPOR(KIDIA,KFDIA,KLON,KLEVS,&
 & PTSPHY,&
 & PWSAM1M,PTSA,&
 & PSSDP3,&
 & YDSOIL,YDCST,&
 & LDLAND,&
 & PRHSW)

USE PARKIND1        , ONLY : JPIM, JPRB
USE YOMHOOK         , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOS_SOIL        , ONLY : TSOIL
USE YOS_CST         , ONLY : TCST
USE YOMSURF_SSDP_MOD, ONLY : SSDP3D_ID
USE SRFWVAPOR_COEF_MOD, ONLY : SRFWVAPOR_COEF

! (C) Copyright 2026- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

!**** *SRFWVAPOR* -  ADDS AN EXPLICIT SOIL WATER-VAPOUR FLUX
!                     CORRECTION TO THE SOIL MOISTURE RIGHT-HAND SIDE

!     PURPOSE.
!     --------
!     THIS ROUTINE ADDS THE PHILIP & DE VRIES (1957) VAPOUR-DIFFUSION
!     EXCHANGE BETWEEN SOIL LAYERS TO *PRHSW*, THE RIGHT-HAND SIDE OF
!     THE SOIL MOISTURE TRIDIAGONAL SYSTEM ALREADY BUILT BY
!     *SRFWEXC_VG* (OR *SRFWEXC*). IT IS PURELY ADDITIVE: THE LIQUID
!     DIFFUSIVITY MATRIX (*PCFW*) BUILT BY THOSE ROUTINES IS NOT
!     TOUCHED, AND *SRFWDIF* or *SRFWINC* DOWNSTREAM ARE UNCHANGED.

!     THIS TARGETS DRYLAND SOIL-MOISTURE BIAS: WHERE LIQUID HYDRAULIC
!     CONDUCTIVITY COLLAPSES NEAR THE RESIDUAL-MOISTURE END OF THE
!     VAN GENUCHTEN CURVE, THE EXISTING RICHARDS-TYPE SOLVE HAS NO
!     MECHANISM FOR THE TEMPERATURE- AND HUMIDITY-GRADIENT-DRIVEN
!     VAPOUR REDISTRIBUTION THAT DOMINATES SOIL WATER MOVEMENT THERE.

!     THE PER-INTERFACE PHYSICS (VAN GENUCHTEN MATRIC HEAD, KELVIN
!     RELATIVE HUMIDITY, EFFECTIVE VAPOUR DIFFUSIVITY) IS COMPUTED BY
!     *SRFWVAPOR_COEF*; THIS ROUTINE ONLY LOOPS OVER INTERFACES AND
!     GRIDPOINTS AND ACCUMULATES THE RESULTING FLUX DIVERGENCE.

!     THIS IS A DELIBERATELY EXPLICIT (NOT SEMI-IMPLICIT) CORRECTION:
!     IT USES THE INCOMING (T-1) MOISTURE PROFILE AND THE
!     ALREADY-UPDATED (CURRENT TIMESTEP) SOIL TEMPERATURE FROM *SRFT*,
!     RATHER THAN BEING FOLDED INTO THE *PCFW* IMPLICIT MATRIX. THIS
!     KEEPS THE ADDITION SIMPLE TO VALIDATE IN ISOLATION FOR A FIRST
!     OFFLINE PROTOTYPE; LINEARISING IT INTO THE IMPLICIT SYSTEM (AND
!     DERIVING TL/AD) IS A NATURAL FOLLOW-ON ONCE THE PHYSICS ITSELF
!     IS VALIDATED, NOT DONE HERE.

!     NO SURFACE (SOIL-ATMOSPHERE) FLUX IS ADDED: ONLY INTERNAL
!     INTER-LAYER REDISTRIBUTION, I.E. A ZERO-FLUX CONDITION AT THE
!     TOP AND BOTTOM OF THE SOIL COLUMN FOR THIS VAPOUR TERM.

!**   INTERFACE.
!     ----------
!          *SRFWVAPOR* IS CALLED FROM *SURFTSTP*, AFTER *SRFT* (SO
!     THAT THE CURRENT-TIMESTEP SOIL TEMPERATURE IS AVAILABLE) AND
!     AFTER *SRFWEXC_VG* or *SRFWEXC* (SO PRHSW ALREADY HOLDS THE LIQUID
!     BUDGET), BUT BEFORE *SRFWDIF*.

!     PARAMETER   DESCRIPTION                                    UNITS
!     ---------   -----------                                    -----

!     INPUT PARAMETERS (INTEGER):
!    *KIDIA*      START POINT
!    *KFDIA*      END POINT
!    *KLON*       NUMBER OF GRID POINTS PER PACKET
!    *KLEVS*      NUMBER OF ACTIVE SOIL-WATER LAYERS (KLEVS_WB AT THE
!                 CALL SITE, MATCHING THE SUBSEQUENT *SRFWDIF* CALL)

!     INPUT PARAMETERS (REAL):
!    *PTSPHY*     TIME STEP                                       S
!    *PWSAM1M*    MULTI-LAYER SOIL MOISTURE AT T-1              M**3/M**3
!    *PTSA*       UPDATED (CURRENT TIMESTEP) SOIL TEMPERATURE      K
!    *PSSDP3*     SPATIALLY DISTRIBUTED SOIL PARAMETERS (VAN
!                 GENUCHTEN ALPHA/N/M, WSAT, WREST, ...)

!     INPUT PARAMETERS (LOGICAL):
!    *LDLAND*     LAND/SEA MASK (TRUE/FALSE)

!     INPUT PARAMETERS (DERIVED TYPE):
!    *YDSOIL*     SOIL PARAMETERS (USES YDSOIL%RDAW, LAYER THICKNESSES)
!    *YDCST*      PHYSICAL CONSTANTS

!     UPDATED PARAMETERS (REAL):
!    *PRHSW*      RIGHT-HAND SIDE OF SOIL MOISTURE EQUATIONS,
!                 AS BUILT BY *SRFWEXC_VG* or *SRFWEXC*; THE VAPOUR-FLUX
!                 DIVERGENCE IS ADDED TO IT IN PLACE.            M**3/M**3

!     REFERENCE.
!     ----------
!     See *SRFWVAPOR_COEF* for the underlying physics references.

!     Original
!     Prototype for the STEMMUS-SCOPE -> ecLand dryland vapour-flux
!     feasibility study.  2026-08-28
!     ------------------------------------------------------------------

IMPLICIT NONE

! Declaration of arguments

INTEGER(KIND=JPIM), INTENT(IN)   :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN)   :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN)   :: KLON
INTEGER(KIND=JPIM), INTENT(IN)   :: KLEVS

REAL(KIND=JPRB),    INTENT(IN)   :: PTSPHY
REAL(KIND=JPRB),    INTENT(IN)   :: PWSAM1M(:,:)
REAL(KIND=JPRB),    INTENT(IN)   :: PTSA(:,:)
REAL(KIND=JPRB),    INTENT(IN)   :: PSSDP3(:,:,:)
TYPE(TSOIL),         INTENT(IN)  :: YDSOIL
TYPE(TCST),          INTENT(IN)  :: YDCST
LOGICAL,             INTENT(IN)  :: LDLAND(:)

REAL(KIND=JPRB),    INTENT(INOUT):: PRHSW(:,:)

!*         0.2    DECLARATION OF LOCAL VARIABLES.
!                 ----------- -- ----- ----------

REAL(KIND=JPRB) :: ZQVAP(KLON,0:KLEVS)
REAL(KIND=JPRB) :: ZDZ

INTEGER(KIND=JPIM) :: JK, JL
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('SRFWVAPOR_MOD:SRFWVAPOR',0,ZHOOK_HANDLE)

ASSOCIATE(RDAW=>YDSOIL%RDAW, &
 & RWSATM3D=>PSSDP3(:,:,SSDP3D_ID%NRWSATM3D), &
 & RWRESTM3D=>PSSDP3(:,:,SSDP3D_ID%NRWRESTM3D), &
 & RMVGALPHA3D=>PSSDP3(:,:,SSDP3D_ID%NRMVGALPHA3D), &
 & RNFACM3D=>PSSDP3(:,:,SSDP3D_ID%NRNFACM3D), &
 & RMFACM3D=>PSSDP3(:,:,SSDP3D_ID%NRMFACM3D) )

!*         1.    INTERFACE VAPOUR FLUXES (ZERO AT TOP AND BOTTOM
!                BOUNDARIES OF THE ACTIVE SOIL-WATER COLUMN).

ZQVAP(:,:) = 0.0_JPRB

DO JK=1,KLEVS-1
  DO JL=KIDIA,KFDIA
    IF (LDLAND(JL)) THEN
      ZDZ = 0.5_JPRB*(RDAW(JK)+RDAW(JK+1))
      CALL SRFWVAPOR_COEF(PWSAM1M(JL,JK),PWSAM1M(JL,JK+1),PTSA(JL,JK),PTSA(JL,JK+1),ZDZ,&
       & RWSATM3D(JL,JK),RWRESTM3D(JL,JK),RMVGALPHA3D(JL,JK),RNFACM3D(JL,JK),RMFACM3D(JL,JK),&
       & RWSATM3D(JL,JK+1),RWRESTM3D(JL,JK+1),RMVGALPHA3D(JL,JK+1),RNFACM3D(JL,JK+1),RMFACM3D(JL,JK+1),&
       & YDCST,&
       & ZQVAP(JL,JK))
    ENDIF
  ENDDO
ENDDO

!*         2.    ADD THE FLUX DIVERGENCE TO THE RIGHT-HAND SIDE
!                (SAME INFLOW-MINUS-OUTFLOW CONVENTION AS THE
!                GRAVITY TERM IN *SRFWEXC_VG*).

DO JK=1,KLEVS
  DO JL=KIDIA,KFDIA
    IF (LDLAND(JL)) THEN
      PRHSW(JL,JK) = PRHSW(JL,JK)+PTSPHY*(ZQVAP(JL,JK-1)-ZQVAP(JL,JK))/RDAW(JK)
    ENDIF
  ENDDO
ENDDO

END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('SRFWVAPOR_MOD:SRFWVAPOR',1,ZHOOK_HANDLE)

END SUBROUTINE SRFWVAPOR
END MODULE SRFWVAPOR_MOD
