MODULE SUSDP_DFLT_CTL_MOD
CONTAINS
SUBROUTINE SUSDP_DFLT_CTL(KIDIA, KFDIA, PTVL, PTVH, PSLT, KLEVS3D, PSSDP2, PSSDP3, YDVEG, YDSOIL, YDAGS)

USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOS_VEG , ONLY : TVEG
USE YOS_SOIL, ONLY : TSOIL
USE YOS_AGS , ONLY : TAGS
USE YOMSURF_SSDP_MOD

! (C) Copyright 2025- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

!     ---------------------------------------------------------------------------
!**   *SUSDP_DFLT* - INITIALIZE THE SDP PARAMETERS WITH DEFAULT VALUES

!      PURPOSE
!      -------
!      INITIALIZE THE SURFACE SPATIALLY DISTRIBUTED PARAMETERS THAT CAN BE
!      CALIBRATED THROUGH THE READING OF AN EXTERNAL FILE WITH THE DEFAULT VALUES

!      INTERFACE
!      ---------
!      *SUSDP_DFLT* IS CALLED BY *SUINIF1S* AND *SUGRIDG*

!      INPUT PARAMETERS (REAL):
!      *PTVL*        LOW VEGETATION TYPE
!      *PTVH*        HIGH VEGETATION TYPE
!      *PSLT*        SOIL TYPE

!      INPUT PARAMETERS (INTEGER):
!      *KLEVS3D*     NUMBER OF SOIL VERTICAL LEVELS

!      OUTPUT PARAMETERS (REAL):
!      *PSSDP2*      2D OBJECT WITH SURFACE SPATIALLY DISTRIBUTED PARAMETERS
!      *PSSDP3*      3D OBJECT WITH SURFACE SPATIALLY DISTRIBUTED PARAMETERS
!     

!      REFERENCE
!      ---------

!      Original:   Iria Ayan-Miguez (BSC) July 2023

!     --------------------------------------------------------------------------


IMPLICIT NONE

INTEGER(KIND=JPIM), INTENT(IN)  :: KIDIA, KFDIA
REAL(KIND=JPRB),    INTENT(IN)  :: PTVL(:)
REAL(KIND=JPRB),    INTENT(IN)  :: PTVH(:)
REAL(KIND=JPRB),    INTENT(IN)  :: PSLT(:)
REAL(KIND=JPRB),    INTENT(OUT) :: PSSDP2(:,:)
REAL(KIND=JPRB),    INTENT(OUT) :: PSSDP3(:,:,:)
INTEGER(KIND=JPIM), INTENT(IN)  :: KLEVS3D
TYPE(TVEG),         INTENT(IN)  :: YDVEG
TYPE(TSOIL),        INTENT(IN)  :: YDSOIL
TYPE(TAGS),         INTENT(IN)  :: YDAGS

INTEGER(KIND=JPIM) :: JK, JL
REAL(KIND=JPRB) :: ZDEPTH_UPPER, ZDEPTH_LOWER
REAL(KIND=JPRB) :: ZTOTWH, ZTOTWL, ZCUMWH, ZCUMWL, ZWH, ZWL
REAL(KIND=JPRB), PARAMETER :: RZROOTDEPTH_MIN=0.1_JPRB ! floor for the vegetation/capacity-matched RDMAXROOT, see below
INTEGER(KIND=JPIM) :: IVTH(KFDIA-KIDIA+1), IVTL(KFDIA-KIDIA+1)
LOGICAL :: LLODDVTYPE(KFDIA-KIDIA+1)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('SUSDP_DFLT_CTL_MOD:SUSDP_DFLT_CTL',0,ZHOOK_HANDLE)
ASSOCIATE(RVCOVH2D=>PSSDP2(:,SSDP2D_ID%NRVCOVH2D), RVCOVL2D=>PSSDP2(:,SSDP2D_ID%NRVCOVL2D),&
    & RVHSTRH2D=>PSSDP2(:,SSDP2D_ID%NRVHSTRH2D), RVHSTRL2D=>PSSDP2(:,SSDP2D_ID%NRVHSTRL2D),&
    & RVLAMSKH2D=>PSSDP2(:,SSDP2D_ID%NRVLAMSKH2D), RVLAMSKL2D=>PSSDP2(:,SSDP2D_ID%NRVLAMSKL2D),&
    & RVLAMSKSH2D=>PSSDP2(:,SSDP2D_ID%NRVLAMSKSH2D), RVLAMSKSL2D=>PSSDP2(:,SSDP2D_ID%NRVLAMSKSL2D),&
    & RVRSMINH2D=>PSSDP2(:,SSDP2D_ID%NRVRSMINH2D), RVRSMINL2D=>PSSDP2(:,SSDP2D_ID%NRVRSMINL2D),&
    & RVZ0MH2D=>PSSDP2(:,SSDP2D_ID%NRVZ0MH2D), RVZ0ML2D=>PSSDP2(:,SSDP2D_ID%NRVZ0ML2D),&
    & RVZ0HH2D=>PSSDP2(:,SSDP2D_ID%NRVZ0HH2D), RVZ0HL2D=>PSSDP2(:,SSDP2D_ID%NRVZ0HL2D),&
    & RVRSMINB2D=>PSSDP2(:,SSDP2D_ID%NRVRSMINB2D),&
    & RDMAXROOTH2D=>PSSDP2(:,SSDP2D_ID%NRDMAXROOTH2D), RDMAXROOTL2D=>PSSDP2(:,SSDP2D_ID%NRDMAXROOTL2D),&
    & RVROOTSAH3D=>PSSDP3(:,:,SSDP3D_ID%NRVROOTSAH3D), RVROOTSAL3D=>PSSDP3(:,:,SSDP3D_ID%NRVROOTSAL3D),&
    & RCGDRYM3D=>PSSDP3(:,:,SSDP3D_ID%NRCGDRYM3D), RLAMBDAM3D=>PSSDP3(:,:,SSDP3D_ID%NRLAMBDAM3D),&
    & RMVGALPHA3D=>PSSDP3(:,:,SSDP3D_ID%NRMVGALPHA3D), RNFACM3D=>PSSDP3(:,:,SSDP3D_ID%NRNFACM3D),&
    & RWCONSM3D=>PSSDP3(:,:,SSDP3D_ID%NRWCONSM3D), RWRESTM3D=>PSSDP3(:,:,SSDP3D_ID%NRWRESTM3D),&
    & RWSATM3D=>PSSDP3(:,:,SSDP3D_ID%NRWSATM3D),&
    & RVAHL2D=>PSSDP2(:,SSDP2D_ID%NRVAHL2D),&
    & RVAMMAXH2D=>PSSDP2(:,SSDP2D_ID%NRVAMMAXH2D), RVAMMAXL2D=>PSSDP2(:,SSDP2D_ID%NRVAMMAXL2D),&
    & RVBHL2D=>PSSDP2(:,SSDP2D_ID%NRVBHL2D),&
    & RVCEH2D=>PSSDP2(:,SSDP2D_ID%NRVCEH2D), RVCEL2D=>PSSDP2(:,SSDP2D_ID%NRVCEL2D),&
    & RVCFH2D=>PSSDP2(:,SSDP2D_ID%NRVCFH2D), RVCFL2D=>PSSDP2(:,SSDP2D_ID%NRVCFL2D),&
    & RVCNAH2D=>PSSDP2(:,SSDP2D_ID%NRVCNAH2D), RVCNAL2D=>PSSDP2(:,SSDP2D_ID%NRVCNAL2D),&
    & RVDMAXH2D=>PSSDP2(:,SSDP2D_ID%NRVDMAXH2D), RVDMAXL2D=>PSSDP2(:,SSDP2D_ID%NRVDMAXL2D),&
    & RVEPSOH2D=>PSSDP2(:,SSDP2D_ID%NRVEPSOH2D), RVEPSOL2D=>PSSDP2(:,SSDP2D_ID%NRVEPSOL2D),&
    & RVF2IH2D=>PSSDP2(:,SSDP2D_ID%NRVF2IH2D), RVF2IL2D=>PSSDP2(:,SSDP2D_ID%NRVF2IL2D),&
    & RVFZEROSTH2D=>PSSDP2(:,SSDP2D_ID%NRVFZEROSTH2D), RVFZEROSTL2D=>PSSDP2(:,SSDP2D_ID%NRVFZEROSTL2D),&
    & RVGAMMH2D=>PSSDP2(:,SSDP2D_ID%NRVGAMMH2D), RVGAMML2D=>PSSDP2(:,SSDP2D_ID%NRVGAMML2D),&
    & RVGCH2D=>PSSDP2(:,SSDP2D_ID%NRVGCH2D), RVGCL2D=>PSSDP2(:,SSDP2D_ID%NRVGCL2D),&
    & RVGMESH2D=>PSSDP2(:,SSDP2D_ID%NRVGMESH2D), RVGMESL2D=>PSSDP2(:,SSDP2D_ID%NRVGMESL2D),&
    & RVLAIMINH2D=>PSSDP2(:,SSDP2D_ID%NRVLAIMINH2D), RVLAIMINL2D=>PSSDP2(:,SSDP2D_ID%NRVLAIMINL2D),&
    & RVQDAMMAXH2D=>PSSDP2(:,SSDP2D_ID%NRVQDAMMAXH2D), RVQDAMMAXL2D=>PSSDP2(:,SSDP2D_ID%NRVQDAMMAXL2D),&
    & RVQDGAMMH2D=>PSSDP2(:,SSDP2D_ID%NRVQDGAMMH2D), RVQDGAMML2D=>PSSDP2(:,SSDP2D_ID%NRVQDGAMML2D),&
    & RVQDGMESH2D=>PSSDP2(:,SSDP2D_ID%NRVQDGMESH2D), RVQDGMESL2D=>PSSDP2(:,SSDP2D_ID%NRVQDGMESL2D),&
    & RVSEFOLDH2D=>PSSDP2(:,SSDP2D_ID%NRVSEFOLDH2D), RVSEFOLDL2D=>PSSDP2(:,SSDP2D_ID%NRVSEFOLDL2D),&
    & RVT1AMMAXH2D=>PSSDP2(:,SSDP2D_ID%NRVT1AMMAXH2D), RVT1AMMAXL2D=>PSSDP2(:,SSDP2D_ID%NRVT1AMMAXL2D),&
    & RVT1GMESH2D=>PSSDP2(:,SSDP2D_ID%NRVT1GMESH2D), RVT1GMESL2D=>PSSDP2(:,SSDP2D_ID%NRVT1GMESL2D),&
    & RVT2AMMAXH2D=>PSSDP2(:,SSDP2D_ID%NRVT2AMMAXH2D), RVT2AMMAXL2D=>PSSDP2(:,SSDP2D_ID%NRVT2AMMAXL2D),&
    & RVT2GMESH2D=>PSSDP2(:,SSDP2D_ID%NRVT2GMESH2D), RVT2GMESL2D=>PSSDP2(:,SSDP2D_ID%NRVT2GMESL2D),&
    & RVTOPTH2D=>PSSDP2(:,SSDP2D_ID%NRVTOPTH2D), RVTOPTL2D=>PSSDP2(:,SSDP2D_ID%NRVTOPTL2D),&
    & RXBOMEGAMH2D=>PSSDP2(:,SSDP2D_ID%NRXBOMEGAMH2D), RXBOMEGAML2D=>PSSDP2(:,SSDP2D_ID%NRXBOMEGAML2D))

! Vegetation Parameters

RVCOVH2D(:)    = YDVEG%RVCOV(NINT(PTVH(KIDIA:KFDIA)))
RVCOVL2D(:)    = YDVEG%RVCOV(NINT(PTVL(KIDIA:KFDIA)))
RVHSTRH2D(:)   = YDVEG%RVHSTR(NINT(PTVH(KIDIA:KFDIA)))
RVHSTRL2D(:)   = YDVEG%RVHSTR(NINT(PTVL(KIDIA:KFDIA)))
RVLAMSKH2D(:)  = YDVEG%RVLAMSK(NINT(PTVH(KIDIA:KFDIA)))
RVLAMSKL2D(:)  = YDVEG%RVLAMSK(NINT(PTVL(KIDIA:KFDIA)))
RVLAMSKSH2D(:) = YDVEG%RVLAMSKS(NINT(PTVH(KIDIA:KFDIA)))
RVLAMSKSL2D(:) = YDVEG%RVLAMSKS(NINT(PTVL(KIDIA:KFDIA)))
RVRSMINH2D(:)  = YDVEG%RVRSMIN(NINT(PTVH(KIDIA:KFDIA)))
RVRSMINL2D(:)  = YDVEG%RVRSMIN(NINT(PTVL(KIDIA:KFDIA)))
RVZ0MH2D(:)    = YDVEG%RVZ0M(NINT(PTVH(KIDIA:KFDIA)))
RVZ0ML2D(:)    = YDVEG%RVZ0M(NINT(PTVL(KIDIA:KFDIA)))
RVZ0HH2D(:)    = YDVEG%RVZ0H(NINT(PTVH(KIDIA:KFDIA)))
RVZ0HL2D(:)    = YDVEG%RVZ0H(NINT(PTVL(KIDIA:KFDIA)))
RVRSMINB2D(:)  = 50.0_JPRB

IVTH(:) = NINT(PTVH(KIDIA:KFDIA))
IVTL(:) = NINT(PTVL(KIDIA:KFDIA))
! Zero-root-depth types (desert=8, ice=12, water=14, ocean=15, water/land
! mix=20): SRFROOTFR pins these entirely to layer 1 and skips them for the
! same reason the Zeng exponential does -- there's no meaningful rooting
! depth to assign. Leave them on the YDVEG%RVROOTSA(1,.)=1 default even
! when LEUNIFORMROOT is active, rather than giving bare ground/water/ice
! points an artificial uniform root profile.
LLODDVTYPE(:) = .FALSE.
DO JL=1,SIZE(IVTH)
  LLODDVTYPE(JL) = ANY(IVTH(JL) == (/8,12,14,15,20/)) .OR. ANY(IVTL(JL) == (/8,12,14,15,20/))
ENDDO

! Soil Parameters (moved ahead of root fraction: the LEUNIFORMROOT default
! below needs RWSATM3D/RWRESTM3D already populated to weight depth by local
! plant-available capacity)

RCGDRYM3D(:,:)  = 1.6E6_JPRB
DO JK=1, KLEVS3D
  RLAMBDAM3D(:,JK) = YDSOIL%RLAMBDAM(NINT(PSLT(KIDIA:KFDIA)))
  RMVGALPHA3D(:,JK)= YDSOIL%RMVGALPHA(NINT(PSLT(KIDIA:KFDIA)))
  RNFACM3D(:,JK)   = YDSOIL%RNFACM(NINT(PSLT(KIDIA:KFDIA)))
  RWCONSM3D(:,JK)  = YDSOIL%RWCONSM(NINT(PSLT(KIDIA:KFDIA)))
  RWRESTM3D(:,JK)  = YDSOIL%RWRESTM(NINT(PSLT(KIDIA:KFDIA)))
  RWSATM3D(:,JK)   = YDSOIL%RWSATM(NINT(PSLT(KIDIA:KFDIA)))
ENDDO

! Prototype: RDMAXROOTH2D/RDMAXROOTL2D (per-point, per-canopy-layer maximum
! rooting depth for LEUNIFORMROOT) default to a vegetation- AND soil-texture-
! dependent value derived entirely from quantities ecLand already has, used
! whenever YDSOIL%RDMAXROOT is not pinned to a fixed positive override (see
! below). Method: take the *existing* Zeng et al. (1998) root-fraction
! profile for this point's vegetation type (YDVEG%RVROOTSA, still computed
! unconditionally by SRFROOTFR in SUSVEG) and weight it by local
! plant-available capacity proxy (RWSATM3D-RWRESTM3D per layer -- the true
! field-capacity-to-wilting-point range isn't available yet at this point in
! the call sequence, since it's derived from these same fields later in
! SUSDP_DERIV; saturation-minus-residual is a coarser but monotonic, always-
! available stand-in). RDMAXROOT is then set to the depth containing 95% of
! that capacity-weighted root profile -- i.e. "how deep would a uniform
! profile need to reach to draw on approximately the same plant-available
! water pool the current Zeng profile already does for this vegetation type
! and this point's own soil". This is a direct CDF-percentile calculation
! (monotonic, always well-posed), not an attempt to match an absolute
! capacity value via the uniform formula's own 1/RDMAXROOT normalisation --
! that turns out non-monotonic (can have zero or two solutions) and isn't
! used here.
DO JL=1,SIZE(IVTH)
  RDMAXROOTH2D(JL) = SUM(YDSOIL%RDAW(1:KLEVS3D))  ! fallback: whole column
  RDMAXROOTL2D(JL) = RDMAXROOTH2D(JL)
  ZTOTWH = 0.0_JPRB
  ZTOTWL = 0.0_JPRB
  DO JK=1,KLEVS3D
    ZTOTWH = ZTOTWH + YDVEG%RVROOTSA(JK,IVTH(JL))*MAX(0.0_JPRB,RWSATM3D(JL,JK)-RWRESTM3D(JL,JK))*YDSOIL%RDAW(JK)
    ZTOTWL = ZTOTWL + YDVEG%RVROOTSA(JK,IVTL(JL))*MAX(0.0_JPRB,RWSATM3D(JL,JK)-RWRESTM3D(JL,JK))*YDSOIL%RDAW(JK)
  ENDDO
  ZCUMWH = 0.0_JPRB
  ZCUMWL = 0.0_JPRB
  ZDEPTH_UPPER = 0.0_JPRB
  DO JK=1,KLEVS3D
    ZWH = YDVEG%RVROOTSA(JK,IVTH(JL))*MAX(0.0_JPRB,RWSATM3D(JL,JK)-RWRESTM3D(JL,JK))*YDSOIL%RDAW(JK)
    ZWL = YDVEG%RVROOTSA(JK,IVTL(JL))*MAX(0.0_JPRB,RWSATM3D(JL,JK)-RWRESTM3D(JL,JK))*YDSOIL%RDAW(JK)
    IF (ZTOTWH > 0.0_JPRB .AND. ZCUMWH+ZWH >= 0.95_JPRB*ZTOTWH .AND. ZWH > 0.0_JPRB) THEN
      RDMAXROOTH2D(JL) = MIN(RDMAXROOTH2D(JL), &
       & ZDEPTH_UPPER + YDSOIL%RDAW(JK)*(0.95_JPRB*ZTOTWH-ZCUMWH)/ZWH)
      ZTOTWH = -1.0_JPRB ! mark found, stop overwriting on later JK
    ENDIF
    IF (ZTOTWL > 0.0_JPRB .AND. ZCUMWL+ZWL >= 0.95_JPRB*ZTOTWL .AND. ZWL > 0.0_JPRB) THEN
      RDMAXROOTL2D(JL) = MIN(RDMAXROOTL2D(JL), &
       & ZDEPTH_UPPER + YDSOIL%RDAW(JK)*(0.95_JPRB*ZTOTWL-ZCUMWL)/ZWL)
      ZTOTWL = -1.0_JPRB
    ENDIF
    ZCUMWH = ZCUMWH + ZWH
    ZCUMWL = ZCUMWL + ZWL
    ZDEPTH_UPPER = ZDEPTH_UPPER + YDSOIL%RDAW(JK)
  ENDDO
  RDMAXROOTH2D(JL) = MAX(RDMAXROOTH2D(JL), RZROOTDEPTH_MIN)
  RDMAXROOTL2D(JL) = MAX(RDMAXROOTL2D(JL), RZROOTDEPTH_MIN)
ENDDO
! A fixed positive YDSOIL%RDMAXROOT pins every point to that one depth
! instead (the flat-scalar behaviour used for the AU-DaS sensitivity sweeps
! earlier this session) -- set YDSOIL%RDMAXROOT<=0 (see SUSSOIL) to use the
! vegetation/capacity-matched default above.
IF (YDSOIL%RDMAXROOT > 0.0_JPRB) THEN
  RDMAXROOTH2D(:) = YDSOIL%RDMAXROOT
  RDMAXROOTL2D(:) = YDSOIL%RDMAXROOT
ENDIF

DO JK=1, KLEVS3D
  RVROOTSAH3D(:,JK) = YDVEG%RVROOTSA(JK, IVTH(:))
  RVROOTSAL3D(:,JK) = YDVEG%RVROOTSA(JK, IVTL(:))
  IF (YDSOIL%LEUNIFORMROOT) THEN
! Stevens et al. (2020, Atmosphere, Eq. 5): uniform root density down to
! RDMAXROOTH2D/RDMAXROOTL2D, zero below it. ZDEPTH_UPPER/LOWER are scalars
! (the layer grid itself doesn't vary by point); RDMAXROOTH2D/L2D vary by
! point (and independently by high/low canopy), so the MIN/MAX below
! broadcast correctly across the whole KIDIA:KFDIA vector.
    ZDEPTH_UPPER = SUM(YDSOIL%RDAW(1:JK-1))
    ZDEPTH_LOWER = ZDEPTH_UPPER + YDSOIL%RDAW(JK)
    WHERE (.NOT. LLODDVTYPE(:))
      RVROOTSAH3D(:,JK) = MAX(0.0_JPRB,MIN(RDMAXROOTH2D(:),ZDEPTH_LOWER)-ZDEPTH_UPPER)/RDMAXROOTH2D(:)
      RVROOTSAL3D(:,JK) = MAX(0.0_JPRB,MIN(RDMAXROOTL2D(:),ZDEPTH_LOWER)-ZDEPTH_UPPER)/RDMAXROOTL2D(:)
    ENDWHERE
  ENDIF
ENDDO

! Ags Parameters

RVAHL2D(:)    = YDAGS%RVAH(NINT(PTVL(KIDIA:KFDIA)))
RVAMMAXH2D(:) = YDAGS%RVAMMAX(NINT(PTVH(KIDIA:KFDIA)))
RVAMMAXL2D(:) = YDAGS%RVAMMAX(NINT(PTVL(KIDIA:KFDIA)))
RVBHL2D(:)    = YDAGS%RVBH(NINT(PTVL(KIDIA:KFDIA)))
RVCEH2D(:)    = YDAGS%RVCE(NINT(PTVH(KIDIA:KFDIA)))
RVCEL2D(:)    = YDAGS%RVCE(NINT(PTVL(KIDIA:KFDIA)))
RVCFH2D(:)    = YDAGS%RVCF(NINT(PTVH(KIDIA:KFDIA)))
RVCFL2D(:)    = YDAGS%RVCF(NINT(PTVL(KIDIA:KFDIA)))
RVCNAH2D(:)   = YDAGS%RVCNA(NINT(PTVH(KIDIA:KFDIA)))
RVCNAL2D(:)   = YDAGS%RVCNA(NINT(PTVL(KIDIA:KFDIA)))
RVDMAXH2D(:)  = YDAGS%RVDMAX(NINT(PTVH(KIDIA:KFDIA)))
RVDMAXL2D(:)  = YDAGS%RVDMAX(NINT(PTVL(KIDIA:KFDIA)))
RVEPSOH2D(:)  = YDAGS%RVEPSO(NINT(PTVH(KIDIA:KFDIA)))
RVEPSOL2D(:)  = YDAGS%RVEPSO(NINT(PTVL(KIDIA:KFDIA)))
RVF2IH2D(:)   = YDAGS%RVF2I(NINT(PTVH(KIDIA:KFDIA)))
RVF2IL2D(:)   = YDAGS%RVF2I(NINT(PTVL(KIDIA:KFDIA)))
RVFZEROSTH2D(:) = YDAGS%RVFZEROST(NINT(PTVH(KIDIA:KFDIA)))
RVFZEROSTL2D(:) = YDAGS%RVFZEROST(NINT(PTVL(KIDIA:KFDIA)))
RVGAMMH2D(:)  = YDAGS%RVGAMM(NINT(PTVH(KIDIA:KFDIA)))
RVGAMML2D(:)  = YDAGS%RVGAMM(NINT(PTVL(KIDIA:KFDIA)))
RVGCH2D(:)    = YDAGS%RVGC(NINT(PTVH(KIDIA:KFDIA)))
RVGCL2D(:)    = YDAGS%RVGC(NINT(PTVL(KIDIA:KFDIA)))
RVGMESH2D(:)  = YDAGS%RVGMES(NINT(PTVH(KIDIA:KFDIA)))
RVGMESL2D(:)  = YDAGS%RVGMES(NINT(PTVL(KIDIA:KFDIA)))
RVLAIMINH2D(:)= YDAGS%RVLAIMIN(NINT(PTVH(KIDIA:KFDIA)))
RVLAIMINL2D(:)= YDAGS%RVLAIMIN(NINT(PTVL(KIDIA:KFDIA)))
RVQDAMMAXH2D(:) = YDAGS%RVQDAMMAX(NINT(PTVH(KIDIA:KFDIA)))
RVQDAMMAXL2D(:) = YDAGS%RVQDAMMAX(NINT(PTVL(KIDIA:KFDIA)))
RVQDGAMMH2D(:) = YDAGS%RVQDGAMM(NINT(PTVH(KIDIA:KFDIA)))
RVQDGAMML2D(:) = YDAGS%RVQDGAMM(NINT(PTVL(KIDIA:KFDIA)))
RVQDGMESH2D(:) = YDAGS%RVQDGMES(NINT(PTVH(KIDIA:KFDIA)))
RVQDGMESL2D(:) = YDAGS%RVQDGMES(NINT(PTVL(KIDIA:KFDIA)))
RVSEFOLDH2D(:) = YDAGS%RVSEFOLD(NINT(PTVH(KIDIA:KFDIA)))
RVSEFOLDL2D(:) = YDAGS%RVSEFOLD(NINT(PTVL(KIDIA:KFDIA)))
RVT1AMMAXH2D(:) = YDAGS%RVT1AMMAX(NINT(PTVH(KIDIA:KFDIA)))
RVT1AMMAXL2D(:) = YDAGS%RVT1AMMAX(NINT(PTVL(KIDIA:KFDIA)))
RVT1GMESH2D(:)  = YDAGS%RVT1GMES(NINT(PTVH(KIDIA:KFDIA)))
RVT1GMESL2D(:)  = YDAGS%RVT1GMES(NINT(PTVL(KIDIA:KFDIA)))
RVT2AMMAXH2D(:) = YDAGS%RVT2AMMAX(NINT(PTVH(KIDIA:KFDIA)))
RVT2AMMAXL2D(:) = YDAGS%RVT2AMMAX(NINT(PTVL(KIDIA:KFDIA)))
RVT2GMESH2D(:)  = YDAGS%RVT2GMES(NINT(PTVH(KIDIA:KFDIA)))
RVT2GMESL2D(:)  = YDAGS%RVT2GMES(NINT(PTVL(KIDIA:KFDIA)))
RVTOPTH2D(:)    = YDAGS%RVTOPT(NINT(PTVH(KIDIA:KFDIA)))
RVTOPTL2D(:)    = YDAGS%RVTOPT(NINT(PTVL(KIDIA:KFDIA)))
RXBOMEGAMH2D(:) = YDAGS%RXBOMEGAM(NINT(PTVH(KIDIA:KFDIA)))
RXBOMEGAML2D(:) = YDAGS%RXBOMEGAM(NINT(PTVL(KIDIA:KFDIA)))

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUSDP_DFLT_CTL_MOD:SUSDP_DFLT_CTL',1,ZHOOK_HANDLE)
END SUBROUTINE SUSDP_DFLT_CTL
END MODULE SUSDP_DFLT_CTL_MOD
