MODULE YOS_SURF
 
USE YOS_AGS     , ONLY : TAGS
USE YOS_AGF     , ONLY : TAGF
USE YOS_CST     , ONLY : TCST
USE YOS_DIM     , ONLY : TDIM
USE YOS_EXC     , ONLY : TEXC
USE YOS_FLAKE   , ONLY : TFLAKE
USE YOS_LW      , ONLY : TLW
USE YOS_MLM     , ONLY : TMLM
USE YOS_OCEAN_ML, ONLY : TOCEAN_ML
USE YOS_RAD     , ONLY : TRAD
USE YOS_RDI     , ONLY : TRDI
USE YOS_SOIL    , ONLY : TSOIL
USE YOS_SW      , ONLY : TSW
USE YOS_VEG     , ONLY : TVEG
USE YOS_BVOC    , ONLY : TBVOC
USE YOS_URB     , ONLY : TURB

! (C) Copyright 2005- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

IMPLICIT NONE

PRIVATE

TYPE, PUBLIC :: TSURF
  TYPE(TAGS)      :: YAGS
  TYPE(TAGF)      :: YAGF
  TYPE(TCST)      :: YCST
  TYPE(TDIM)      :: YDIM
  TYPE(TEXC)      :: YEXC
  TYPE(TFLAKE)    :: YFLAKE
  TYPE(TLW)       :: YLW
  TYPE(TMLM)      :: YMLM
  TYPE(TOCEAN_ML) :: YOCEAN_ML
  TYPE(TRAD)      :: YRAD
  TYPE(TRDI)      :: YRDI
  TYPE(TSOIL)     :: YSOIL
  TYPE(TSW)       :: YSW
  TYPE(TVEG)      :: YVEG
  TYPE(TBVOC)     :: YBVOC
  TYPE(TURB)      :: YURB

  CONTAINS

  PROCEDURE :: UPDATE_DEVICE => TSURF_UPDATE_DEVICE
  PROCEDURE :: WIPE_DEVICE => TSURF_WIPE_DEVICE
END TYPE TSURF

! Single global surface metadata object.
TYPE(TSURF), PUBLIC, SAVE :: YSURF

CONTAINS

SUBROUTINE TSURF_UPDATE_DEVICE(SELF, LCREATED)
  CLASS(TSURF) :: SELF
  LOGICAL, OPTIONAL, INTENT(IN) :: LCREATED
  LOGICAL :: LLCREATED

  LLCREATED = .FALSE.
  IF(PRESENT(LCREATED)) LLCREATED = LCREATED
  IF(.NOT. LLCREATED)THEN
    !$acc enter data create(SELF)
    !$acc update device(SELF)
  ENDIF

  CALL SELF%YAGS%UPDATE_DEVICE(LCREATED=.TRUE.)
  CALL SELF%YVEG%UPDATE_DEVICE(LCREATED=.TRUE.)
  CALL SELF%YAGF%UPDATE_DEVICE(LCREATED=.TRUE.)
  CALL SELF%YMLM%UPDATE_DEVICE(LCREATED=.TRUE.)
  CALL SELF%YOCEAN_ML%UPDATE_DEVICE(LCREATED=.TRUE.)
  CALL SELF%YSOIL%UPDATE_DEVICE(LCREATED=.TRUE.)
  CALL SELF%YSW%UPDATE_DEVICE(LCREATED=.TRUE.)

END SUBROUTINE TSURF_UPDATE_DEVICE

SUBROUTINE TSURF_WIPE_DEVICE(SELF, LDELETED)
  CLASS(TSURF) :: SELF
  LOGICAL, OPTIONAL, INTENT(IN) :: LDELETED
  LOGICAL :: LLDELETED

  LLDELETED = .FALSE.
  IF(PRESENT(LDELETED)) LLDELETED = LDELETED

  CALL SELF%YAGS%WIPE_DEVICE(LDELETED=.TRUE.)
  CALL SELF%YVEG%WIPE_DEVICE(LDELETED=.TRUE.)
  CALL SELF%YAGF%WIPE_DEVICE(LDELETED=.TRUE.)
  CALL SELF%YMLM%WIPE_DEVICE(LDELETED=.TRUE.)
  CALL SELF%YOCEAN_ML%WIPE_DEVICE(LDELETED=.TRUE.)
  CALL SELF%YSOIL%WIPE_DEVICE(LDELETED=.TRUE.)
  CALL SELF%YSW%WIPE_DEVICE(LDELETED=.TRUE.)

  IF(.NOT. LLDELETED)THEN
    !$acc exit data delete (SELF) finalize
  ENDIF
END SUBROUTINE TSURF_WIPE_DEVICE

END MODULE YOS_SURF

